/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guelphhackmodchatclient;

import java.awt.event.KeyEvent;
import javax.swing.JTextArea;

/**
 *
 * @author Guest User
 */
public class GuelphHackChat extends javax.swing.JFrame {

    /**
     * Creates new form GuelphHackUI
     */
    public GuelphHackChat() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miscCheckBox = new javax.swing.JCheckBox();
        myAccountButton = new javax.swing.JButton();
        currChatLabel = new java.awt.Label();
        userScrollPane = new javax.swing.JScrollPane();
        chatBoxEntryScrollPane = new javax.swing.JScrollPane();
        chatBoxEntry = new javax.swing.JTextArea();
        usersLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        roomListLabel = new javax.swing.JLabel();
        socialAnxientyButton = new javax.swing.JButton();
        depressionButton = new javax.swing.JButton();
        schoolStresserButton = new javax.swing.JButton();
        griefLossButton = new javax.swing.JButton();
        chatBoxScrollPane = new javax.swing.JScrollPane();
        chatBox = new javax.swing.JTextArea();

        miscCheckBox.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        myAccountButton.setText("Account");

        currChatLabel.setAlignment(java.awt.Label.CENTER);
        currChatLabel.setText("Current Chat");

        chatBoxEntry.setColumns(20);
        chatBoxEntry.setRows(5);
        chatBoxEntry.setLineWrap(true);
        chatBoxEntry.setWrapStyleWord(true);
        chatBoxEntry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chatBoxEntryKeyTyped(evt);
            }
        });
        chatBoxEntryScrollPane.setViewportView(chatBoxEntry);

        usersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usersLabel.setText("Users");

        roomListLabel.setText("    Chatrooms:");

        socialAnxientyButton.setText("Social Anxiety");
        socialAnxientyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialAnxientyButtonActionPerformed(evt);
            }
        });

        depressionButton.setText("Depression");
        depressionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depressionButtonActionPerformed(evt);
            }
        });

        schoolStresserButton.setText("School Stressers");
        schoolStresserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolStresserButtonActionPerformed(evt);
            }
        });

        griefLossButton.setText("Grief & Loss");
        griefLossButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                griefLossButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(socialAnxientyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(depressionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(schoolStresserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(griefLossButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(roomListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(socialAnxientyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depressionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(schoolStresserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(griefLossButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        chatBox.setColumns(20);
        chatBox.setRows(5);
        chatBox.setFocusable(false);
        chatBox.setLineWrap(true);
        chatBox.setWrapStyleWord(true);
        chatBoxScrollPane.setViewportView(chatBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chatBoxEntryScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(currChatLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chatBoxScrollPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userScrollPane)
                    .addComponent(usersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currChatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(chatBoxScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatBoxEntryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(userScrollPane)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        currChatLabel.getAccessibleContext().setAccessibleName("currentChat");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printMessage(GuelphHackMessage m){
        
    }
    
    private void setCurrentChat(GuelphHackChatroom c){
        clearChatBox(this.chatBox);
        
    }
    
    private void socialAnxientyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialAnxientyButtonActionPerformed
        // TODO add your handling code here:
        currChatLabel.setText(this.socAnxRoom.getChatroomName());
        setCurrentChat(this.socAnxRoom);
    }//GEN-LAST:event_socialAnxientyButtonActionPerformed

    private void depressionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depressionButtonActionPerformed
        // TODO add your handling code here:
        currChatLabel.setText(this.depresRoom.getChatroomName());
        setCurrentChat(this.depresRoom);
    }//GEN-LAST:event_depressionButtonActionPerformed

    private void schoolStresserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolStresserButtonActionPerformed
        // TODO add your handling code here:
        currChatLabel.setText(this.schoolRoom.getChatroomName());
        setCurrentChat(this.schoolRoom);
    }//GEN-LAST:event_schoolStresserButtonActionPerformed

    private void griefLossButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_griefLossButtonActionPerformed
        // TODO add your handling code here:
        currChatLabel.setText(this.grief2Room.getChatroomName());
        setCurrentChat(this.grief2Room);
    }//GEN-LAST:event_griefLossButtonActionPerformed

    private void sendMessage(String user, String message){
        System.out.println(user+": "+message);
        //this.chatBox.setText(user+": "+message);
        this.chatBox.append(user+": "+message+"\n");
    }   
    
    private void clearChatBox(JTextArea j){
        j.setText("");
    }
    
    private void chatBoxEntryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chatBoxEntryKeyTyped
        // TODO add your handling code here:
        //System.out.println("|"+evt.getKeyChar()+"|");
        if (evt.getKeyChar() == '\n'){
            sendMessage("Mod",chatBoxEntry.getText().trim());
            clearChatBox(this.chatBoxEntry);
        //JOptionPane.showMessageDialog(null , "You've Submitted the name " + nameInput.getText());
        } else {
            //System.out.println("key typed");
        }
    }//GEN-LAST:event_chatBoxEntryKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuelphHackChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuelphHackChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuelphHackChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuelphHackChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuelphHackChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatBox;
    private javax.swing.JTextArea chatBoxEntry;
    private javax.swing.JScrollPane chatBoxEntryScrollPane;
    private javax.swing.JScrollPane chatBoxScrollPane;
    private java.awt.Label currChatLabel;
    private javax.swing.JButton depressionButton;
    private javax.swing.JButton griefLossButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox miscCheckBox;
    private javax.swing.JButton myAccountButton;
    private javax.swing.JLabel roomListLabel;
    private javax.swing.JButton schoolStresserButton;
    private javax.swing.JButton socialAnxientyButton;
    private javax.swing.JScrollPane userScrollPane;
    private javax.swing.JLabel usersLabel;
    // End of variables declaration//GEN-END:variables
    private GuelphHackChatroom socAnxRoom = new GuelphHackChatroom("Social Anxiety");
    private GuelphHackChatroom depresRoom = new GuelphHackChatroom("Depression");
    private GuelphHackChatroom schoolRoom = new GuelphHackChatroom("School Stressers");
    private GuelphHackChatroom grief2Room = new GuelphHackChatroom("Grief & Loss");
}
